### ISSUE TITLE
learningModule Image display returns 500 

### ISSUE THREAD

**Issue by pixeline** [becodeorg/Learning2gether-platform#346]
Where to see the error: Create a new module, upload an image, then further edit the module on a URL like: https://platform.learning2gether.org/partner/edit/module/3

The image uploaded in the previous step is not displayed : the upload is okay (the image is in the public/upload folder) but the display returns 500.

## investigation
The template  uses the `asset()` function.

```twig
<div class="col">
  <p>{{ 'Current image' | trans }}</p>
      {% if module.image != '' %}
           <img style="width: 180px;" src="{{ asset(module.image | imagine_filter('learningModuleImage')) }}" alt="">
       {% endif %}
</div>
```

If I do this from the console:
```bash
sudo ./bin/console liip:imagine:cache:resolve f32b18e6fa571f001b94f0a1bfe48a8d.png --filter=learningModuleImage
``` 
And then reload the page, then it works !

So the issue is in the liip_imagine routing I guess ?

**Comment by pixeline** [comment]
Question posted to [Stack Overflow](https://stackoverflow.com/questions/60628712/symfony-liip-imagine-image-path-resolution-results-in-404)

**Comment by pixeline** [comment]
I solved it !

this was the winning configuration:

```yml

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%kernel.project_dir%/public/upload"
                    - "%kernel.project_dir%/public/assets/img"

    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: media/cache

    filter_sets:
        cache: ~
        learningModuleImage:
            cache: default
            filters:
                downscale:
                    max: [512, 512]
        profile:
            filters:
                downscale:
                    max: [512, 512]

        # the name of the "filter set"
        thumb:
            # adjust the image quality to 75%
            # quality: 75
            cache: default
            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [128, 128], mode: outbound }
                # create a 2px black border: center the thumbnail on a black background
                # 4px larger to create a 2px border around the final image
                # background: { size: [124, 94], position: center, color: '#000000' }

```
